
apiVersion: v1
metadata:
  name: Feature XYZ
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - cypress/integration/example.test.js
image:
  base: saucelabs/stt-cypress-mocha-node
  version: latest
sauce:
  region: us-west-1
